### PR TITLE
added flutter app router class

### PR DESCRIPTION
**Pull request by ehsankkk1**
app router that was giving by flutter that will make
dependency injection, sending arguments, and making global changes in the future much easier

to add new screen just add the case name in app_router_routes_names.dart  and make the switch case return the screen

using example:  Navigator.of(context).pushNamed(homePage);

### CODE REVIEW

**Comment by BurningAXE** [comment]
@ehsankkk1 I changed the branch from `master` to `dev` as we should work from there. There are conflicts - can you resolve them? Or maybe drop this one and start fresh if it will be easier?

**Comment by BurningAXE** [comment]
@ehsankkk1 I believe this PR become obsolete after another update on the dev branch, right?

**Comment by ehsankkk1** [comment]
> 
@BurningAXE  made a new PR with a new app router yes I think it's absolute

**Comment by BurningAXE** [comment]
Ah, OK, thanks for the clarifications!

**Pull request closed without merging**
