### PR TITLE
Platform Embedding

### PR DESCRIPTION
**Pull request by StructPoltergeist**
- Android, and Web embedding completed, iOS Remaining

- Flutter GitHub Action Workflow added

- GitHub open source community standards met

- Added Go Router for navigation and routing

- Added integration testing

- Added path URL strategy

- Added Localisations

- Added Adaptive App Bars and Adaptive Containers

- Added Google Maps Platform Embedding

- Added Firebase Platform Embedding

- Desktop Platforms are no longer supported due to dependency constraints

- Adding Animations (Next Pull)

- Adding Internationalisation (Next Pull)

### CODE REVIEW

**Comment by BurningAXE** [comment]
Hey @AbdhilahiRahimWabwire! That's for this! 
While I haven't yet reviewed it just wanted to comment that (at least for the time being) we will support only iOS, Android and Web platforms.

**Comment by StructPoltergeist** [comment]
Understood, I will remove the other platforms

**Comment by StructPoltergeist** [comment]
I will commit half of these changes tomorrow and the other half over the next few days.

I have completed the package and widget migrations but still need to complete the Firebase and Google Maps integrations.

**Comment by StructPoltergeist** [comment]
I added back the other platforms just in case you wanted to support them in the far future.

**Comment by BurningAXE** [comment]
> I added back the other platforms just in case you wanted to support them in the far future.

My only concern is that I don't want us to spend time maintaining compatibility with platforms that we don't use. If they come for free - let them be. But if they limit package choice or slow down implementation - better without them.

**Comment by StructPoltergeist** [comment]
They are free, Pub Upgrade automatically updates them using the plugin registrant and they can be generated automatically using the package name.

**Comment by StructPoltergeist** [comment]
Desktop Platforms are no longer supported due to dependency constraints

**Pull request closed without merging**
