### PR TITLE
Easy Localizations Config

### PR DESCRIPTION
**Pull request by muhAzri**
# Easy Localization Config

## Changes

1. Add Android locale.properties into .gitignore
2. Add CFBundleLocalizations in IOS Info.plist
3. Add Localization Strings in Assets 
4. Add Easy Localization Config in Main.Dart

### CODE REVIEW

**Review by StructPoltergeist — DISMISSED** [review]

**Comment by StructPoltergeist** [comment]
Localization is handled by firebase.

**Review by StructPoltergeist — COMMENTED** [review]
Localization is handled by firebase.

**Comment by BurningAXE** [comment]
> Localization is handled by firebase.

Hm, how is it handled by Firebase?

**Comment by StructPoltergeist** [comment]
Read the main.dart. It is at the bottom, it says Firebase localization.

**Pull request closed without merging**
