### PR TITLE
Platform Embedding

### LINKED ISSUE #3: Add side menu
Add a side menu similar to the one in the native Android app

### LINKED ISSUE #4: Add About screen
Add About screen with info about the app. Copy the one in the native apps and make needed assumptions where needed.

### LINKED ISSUE #5: Add a side menu similar to the one in the native Android app with few features
## Description:
I would like to add a side menu to the Android app, similar to the one found in the native Android app. The menu should be accessible by swiping from the left edge of the screen, and should contain a list of items that allow the user to easily navigate to different parts of the app.
I believe that a side menu would greatly improve the user experience and make it easier for users to navigate throughout the app.

## Tasks:
Implement a navigation drawer that slides in from the left edge of the screen
Populate the navigation drawer with a list of items representing different sections of the app
Highlight the currently selected item to indicate where the user currently is in the app
Consider including icons next to each item for easier recognition
Include a header at the top of the navigation drawer displaying the user's name and profile picture, if applicable

## Expected Outcome:
Users will be able to easily navigate throughout the app using the new side menu, which should improve the overall user experience.
Thanks for considering this feature request!

### LINKED ISSUE #9: Create and setup a dev project

### LINKED ISSUE #12: It's worth noting that the setUserPrefs method doesn't return anything, which might be a problem if you want to know when the user preferences have been set.
It's worth noting that the setUserPrefs method doesn't return anything, which might be a problem if you want to know when the user preferences have been set.
# suggestions

### isUserLoggedIn:

Consider renaming this method to something like checkUserLoggedInStatus, as it better describes what the method does.
Consider changing the return type from Future<bool> to just Future, since the method doesn't actually return a boolean value - it returns a Future that resolves to a boolean value.
Consider adding some error handling code in case an error occurs while getting the SharedPreferences instance.
i.e

`
Future checkUserLoggedInStatus() async {
  try {
    final prefs = await SharedPreferences.getInstance();
    bool isLoggedIn = prefs.getBool(global.loggedIn) ?? false;
    return isLoggedIn;
  } catch (e) {
    print('Error getting user logged in status: $e');
    return false;
  }
}
`
### setUserPrefs:

Consider adding a parameter to this method that allows the caller to specify whether the user is logged in or not, rather than always setting the loggedIn key to true.
Consider adding some error handling code in case an error occurs while getting the SharedPreferences instance.
i.e

`
void setUserPrefs({bool isLoggedIn = true}) async {
  try {
    final prefs = await SharedPreferences.getInstance();
    prefs.setBool(global.loggedIn, isLoggedIn);
  } catch (e) {
    print('Error setting user prefs: $e');
  }
}
`

_Originally posted by @samuelkchris in https://github.com/HelpAPaw/Flutter/pull/7#discussion_r1141492768_

### LINKED ISSUE #14: [USER EXPERIENCE] Users should not be able to pop screens and get back to splash
<h3>Issue description:</h3>

Currently, if there's an issue with user experience: one can press the AppBar() "back" button, or the phone's native "back" button and get stuck on splash screen. 

I will research about whether there's good practices on preventing that and, if I find something interesting, I will be sharing with y'all

<h3> Hypothesis: </h3>

There should exist a way to either:

1. Prevent users from popping the homepage window; or
2. Refactor routing in a way users will not be able to pop the homepage screen;

### LINKED ISSUE #16: Add FAQs Screen

### LINKED ISSUE #18: Add Privacy Policy

### PR DESCRIPTION
**Pull request by StructPoltergeist**
- Removed Bloc: Asynchronous - Stream Builders, Inherited and Stateful Widgets

- Android and Web embedding completed, iOS Remaining

- Flutter GitHub Action Workflow added

- GitHub open source community standards met

- Added go_router for navigation and routing

- Added integration testing

- Added path URL strategy

- Added Localisations

- Added Adaptive App Bars and Adaptive Containers

- Added Google Maps Platform Embedding

- Added Firebase Platform Embedding

- Desktop Platforms are no longer supported due to dependency constraints

### CODE REVIEW

**Comment by BurningAXE** [comment]
What is the meaning of "(Next Pull)" in some items?

**Comment by StructPoltergeist** [comment]
Those tasks are not completed in this current pull request. They will need to be merged in the next pull request.

**Comment by BurningAXE** [comment]
Sorry for the delay - quite a lot to review.
Outstanding work!
However, I'm a little hesitant to merge it while the mobile platforms (our main ones) are not building. At the same time I can see why you wouldn't want to swell this PR even more. Maybe you can create a second PR that points to the branch of this one? What do you think?

**Comment by StructPoltergeist** [comment]
I'll fix the mobile platform builds and notify when it is complete to merge this pull request.

**Review by BurningAXE — APPROVED** [review]

**Review by thisaiveerapandian — APPROVED** [review]
much appreciate your work. next time onwards please split the pull request. please don't give all file changes at a time. if something happens we can't revert all the changes.

**Comment by StructPoltergeist** [comment]
> much appreciate your work. next time onwards please split the pull request. please don't give all file changes at a time. if something happens we can't revert all the changes.

@thisaiveerapandian This was a rewrite of the entire application. Without it, the application would not currently be running. It. would still be using Bloc for 6 pages of input. It would not have go_router for navigation and routing. It now runs on Android, Web and iOS. I could not split the pull request.

**Pull request merged**
